version: "1"
services:
  dyndns-noip:
    image: theadzik/dyndns-noip:latest
    volumes:
      - history:/history
    environment:
      LOG_LEVEL: INFO
      NOIP_USERNAME: username
      NOIP_PASSWORD: password
      HOSTNAME: example.ddns.net
#      CHECK_ONLY_MODE: "True" ## Setting any value will cause check only mode to enable
#      SMTP_HOST: mail.example.com # Optional
#      SMTP_PORT: "465" # Optional
#      SMTP_USERNAME: noreply@example.com # Optional
#      SMTP_PASSWORD: "password" # Optional
#      NOTIFICATION_EMAIL: youremail@example.com # Optional
volumes:
  history:
